version: '3.8'

name: web-engineering

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: webEng_RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: webEng_Gateway
    depends_on:
      - rabbitmq
    ports:
      - "13000:13000" # Adjust the port according to your Spring Boot application settings
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

  demoservice:
    build:
      context: .
      dockerfile: Demo/service/Dockerfile
    container_name: webEng_DemoService
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
