spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: 7677e6438e6bec90cac27577d9a3c8928ec79b4d101fc6ee9e86f22d20cc7a88
            client-secret: gloas-36c3c720c9025afca1dc3e6423ec9fd09a0de3d206bb80385764a29c111229a3
            redirect-uri: http://localhost:13000/login/oauth2/code/gitlab
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: https://git.imn.htwk-leipzig.de/oauth/authorize
            token-uri: https://git.imn.htwk-leipzig.de/oauth/token
            user-info-uri: https://git.imn.htwk-leipzig.de/api/v4/user
            user-name-attribute: id
server:
  port: 13000
app:
  oauth2:
    successRedirectUrl: http://localhost:3000
    failRedirectUrl: /loging?error=true
  frontend:
    url: http://localhost:3000
  auth:
    jwt:
      secret: f9db405e92044a75add38205140b66cf61c3c49c31ea47dcbd91820c69e95cdb
      expiration: 10800000 # 3 hours

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/api-docs/swagger-ui.html
    operationsSorter: method